const mineflayer = require('mineflayer');
const bot = mineflayer.createBot({ host: '127.0.0.1', port: 25565, username: 'EmberTester', version: '1.21.11', auth: 'offline' });
const sleep = ms => new Promise(r => setTimeout(r, ms));
const lines = []; bot.on('message', m => lines.push(m.toString()));
const ask = async (x, w = 500) => { const n = lines.length; bot.chat(x); await sleep(w); return lines.slice(n).join(' | '); };
const res = []; const check = (n, ok, note) => { res.push(ok); console.log((ok ? 'PASS ' : 'FAIL ') + n + ' ' + note); };
const count = async sel => {
  await ask('/scoreboard objectives add gdc dummy', 200); await ask('/scoreboard players set #n gdc -1', 200);
  await ask(`/execute store result score #n gdc if entity ${sel}`, 300);
  const r = await ask('/scoreboard players get #n gdc', 500); const m = /has (-?\d+) \[gdc\]/.exec(r) || /(-?\d+)/.exec(r); return m ? +m[1] : NaN; };
const countR = async sel => { for (let k = 0; k < 4; k++) { const v = await count(sel); if (!Number.isNaN(v) && v >= 0) return v; } return NaN; };
const G = '@e[type=emberfall:ember_guardian,limit=1]';
const hp1 = async () => { const r = await ask(`/data get entity ${G} Health`, 500); const m = /: ([\d.]+)f/.exec(r); return m ? +m[1] : NaN; };
const hp = async () => { for (let k = 0; k < 4; k++) { const v = await hp1(); if (!Number.isNaN(v)) return v; } return NaN; };
bot.once('spawn', async () => {
  await sleep(6500);
  await ask('/kill @e[type=!player]', 600); await ask('/kill @e[type=minecraft:item_display]', 600); await sleep(1500);
  await ask('/gamemode survival'); await ask('/effect give @s minecraft:resistance 999 4 true', 300); await ask('/effect give @s minecraft:regeneration 999 4 true', 300);
  await ask('/character select juggernaut', 600); await ask('/expedition', 1500); for (let i = 0; i < 40; i++) { await sleep(1500); if (/expedition/.test(await ask('/data get entity @s Dimension', 400))) break; } await sleep(2500);
  const DISP = '@e[type=minecraft:item_display]';
  const baseDisp = await countR(DISP); console.log('baseline item_displays in the run BEFORE the boss:', baseDisp);
  console.log('boss:', (await ask('/emberfall boss 0', 1200)).slice(0, 100)); await sleep(2500);
  await ask('/emberfall wavestop 0', 400);
  await ask('/kill @e[type=!player,type=!emberfall:ember_guardian,type=!minecraft:item_display]', 600);
  const g = await countR('@e[type=emberfall:ember_guardian]'); check('G0 exactly one Ember Guardian spawned', g === 1, `count=${g}`);
  const h0 = await hp(); check('G0b full health is 600', h0 > 550 && h0 <= 600, `hp=${h0}`);
  const d1 = await countR(DISP); check('G1 exactly 36 display parts added (4 head + 4 tentacles x 8 links)', d1 - baseDisp === 36, `displays=${d1}, baseline=${baseDisp}, added=${d1 - baseDisp}`);
  const tent = await countR('@e[type=minecraft:item_display,tag=emberfall_tentacle]'); check('G1b all 32 tentacle parts carry the tentacle tag', tent === 32, `tagged=${tent}`);
  const before = await hp();
  await ask(`/execute as ${G} run damage @s 40 minecraft:generic`, 700); const after = await hp();
  check('G2 damage lowers hp (stage 1 has no gate)', after < before, `before=${before} after=${after}`);
  await ask('/kill @e[type=emberfall:ember_guardian]', 800); await sleep(4500);
  const g2 = await countR('@e[type=emberfall:ember_guardian]'); const d2 = await countR(DISP);
  check('G3 boss removed after death', g2 === 0, `guardians=${g2}`);
  check('G4 no leaked display parts', d2 <= baseDisp, `displays=${d2}, baseline=${baseDisp}`);
  console.log(res.every(Boolean) ? 'ALL PASS' : 'SOME FAIL');
  bot.quit(); setTimeout(() => process.exit(0), 300);
});
bot.on('error', e => console.log('ERR', e.message));
