const mineflayer = require('mineflayer');
const bot = mineflayer.createBot({ host: '127.0.0.1', port: 25565, username: 'EmberTester', version: '1.21.11', auth: 'offline' });
const sleep = ms => new Promise(r => setTimeout(r, ms));
const lines = []; bot.on('message', m => lines.push(m.toString()));
bot.once('spawn', async () => {
  await sleep(6000);
  const c = async (x, w = 700) => { bot.chat(x); await sleep(w); };
  const ask = async (x, w = 700) => { const n = lines.length; bot.chat(x); await sleep(w); return lines.slice(n).join(' | '); };
  const H = async () => (await ask('/data get entity @s Health', 600)).match(/entity data: (-?[\d.]+)f/)?.[1];
  const M = async () => (await ask('/attribute @s minecraft:max_health get', 600)).match(/value[^\d-]*(-?[\d.]+)/)?.[1];
  await c('/gamemode survival'); await c('/character select vanguard');
  await c('/expedition leave', 900); await c('/expedition', 4000); for (let i = 0; i < 30; i++) { await sleep(1500); if (/expedition/.test(await ask('/data get entity @s Dimension', 400))) break; } await sleep(1500);
  const purge = setInterval(() => bot.chat('/kill @e[type=!player,type=!item]'), 1500);
  await c('/effect clear @s', 300);
  console.log('before heart   : hp', await H(), 'max', await M());
  console.log('give           :', (await ask('/emberfall relic give EmberTester dragons_heart', 700)).slice(0, 120));
  console.log('after give     : hp', await H(), 'max', await M());
  await c('/damage @s 12 minecraft:generic', 700);
  const h0 = Number(await H()); console.log('wounded        : hp', h0);
  await sleep(6000);
  const h1 = Number(await H()); console.log('6 s STILL      : hp', h1, 'gain', (h1 - h0).toFixed(1));
  await c('/damage @s 12 minecraft:generic', 700);
  const w0 = Number(await H()); console.log('wounded again  : hp', w0);
  bot.setControlState('forward', true); const t = setInterval(() => bot.look(bot.entity.yaw + 0.9, 0, true), 400);
  await sleep(6000); bot.clearControlStates(); clearInterval(t); await sleep(400);
  const w1 = Number(await H()); console.log('6 s WALKING    : hp', w1, 'gain', (w1 - w0).toFixed(1));
  console.log('state          :', (await ask('/emberfall relic state EmberTester', 700)).slice(0, 200));
  clearInterval(purge); bot.quit(); setTimeout(() => process.exit(0), 300);
});
