const mineflayer = require('mineflayer');
const bot = mineflayer.createBot({ host: '127.0.0.1', port: 25565, username: 'EmberTester', version: '1.21.11', auth: 'offline' });
const sleep = ms => new Promise(r => setTimeout(r, ms));
const chat = [];
bot.on('error', e => console.log('ERROR', e));
bot.on('kicked', r => console.log('KICKED', JSON.stringify(r)));
bot.on('message', m => { const t = m.toString(); if (t.trim()) chat.push(t); });
const c = async (x, w = 900) => { bot.chat(x); await sleep(w); };
const X = -29, Y = 75, Z = -2;
const TAG = `emberfall_hub_${X}_${Y + 1}_${Z}`;
const say = async (cmd, w = 1000) => { chat.length = 0; await c(cmd, w); return chat.slice(); };
const ents = async () => { const r = (await say(`/execute if entity @e[tag=${TAG},distance=..25]`)).join(' '); const m = r.match(/Count: (\d+)/); return m ? +m[1] : 0; };
const selected = async () => { const r = await say('/character list', 1300); const l = r.find(t => t.trim().startsWith('>')); const m = l && l.match(/\(([a-z_]+)\)/); return m ? m[1] : '(none) ' + r.join('|').slice(0, 120); };
let fails = 0;
const check = (label, ok, extra = '') => { console.log((ok ? 'PASS ' : 'FAIL ') + label + (extra ? '  ' + extra : '')); if (!ok) fails++; };
bot.once('spawn', async () => {
  await sleep(6000);
  await c('/gamemode creative', 700);
  await c(`/tp @s ${X + 0.5} ${Y + 1} ${Z + 6.5}`, 3000);
  await c(`/setblock ${X} ${Y + 1} ${Z} emberfall:ember_hearth`, 900);
  await c(`/emberfall hubactivate ${X} ${Y + 1} ${Z}`, 3000);
  check('hub entity count is 28 (19 + 9 hotspots)', (await ents()) === 28, 'got ' + await ents());
  const r1 = await say('/emberfall hubclick hubact_bust_gravedigger');
  check('click gravedigger bust runs', r1.join(' ').includes('ran=true'), r1.join('|').slice(0, 100));
  const s1 = await selected(); check('selection is now Gravedigger', s1 === 'gravedigger', s1);
  const r2 = await say('/emberfall hubclick hubact_bust_reaper');
  check('click reaper bust runs', r2.join(' ').includes('ran=true'));
  const s2 = await selected(); check('selection moved to Reaper', s2 === 'reaper', s2);
  const r3 = await say('/emberfall trypick nonexistent');
  check('unknown character id is rejected, selection unchanged', /TRYPICK error: Unknown or locked/i.test(r3.join(' ')) && (await selected()) === 'reaper', r3.join('|').slice(0, 100));
  const r4 = await say('/emberfall hubclick hubact_shop', 1500);
  check('click shop runs', r4.join(' ').includes('ran=true'), r4.join('|').slice(0, 100));
  await c(`/setblock ${X} ${Y + 1} ${Z} minecraft:air`, 3000);
  check('teardown removes all 28 entities incl. hotspots', (await ents()) === 0);
  console.log(fails ? `RESULT: ${fails} FAILED` : 'RESULT: ALL PASSED');
  bot.quit(); process.exit(fails ? 1 : 0);
});
