const mineflayer = require('mineflayer');
const sleep = ms => new Promise(r => setTimeout(r, ms));
const X = -29, Y = 75, Z = -2;
const mk = name => new Promise(res => { const b = mineflayer.createBot({ host: '127.0.0.1', port: 25565, username: name, version: '1.21.11', auth: 'offline' }); b.chat_ = []; b.on('message', m => { const t = m.toString(); if (t.trim()) b.chat_.push(t); }); b.on('kicked', r => console.log('KICKED', name, JSON.stringify(r))); b.once('spawn', () => res(b)); });
(async () => {
  const op = await mk('EmberTester'); await sleep(5000);
  const say = async (b, cmd, w = 1000) => { b.chat_.length = 0; b.chat(cmd); await sleep(w); return b.chat_.join(' | '); };
  await say(op, '/gamemode creative', 700);
  await say(op, `/tp @s ${X + 0.5} ${Y + 1} ${Z + 6.5}`, 2500);
  await say(op, `/setblock ${X} ${Y + 1} ${Z} emberfall:ember_hearth`, 900);
  await say(op, `/emberfall hubactivate ${X} ${Y + 1} ${Z}`, 3000);
  const pl = await mk('PlainPlayer'); await sleep(5000);
  const before = await say(pl, '/expedition leave', 1300);
  console.log('PlainPlayer before plate :', before.slice(0, 60), before.includes("not on an expedition") ? '(PASS: not in a run)' : '(FAIL)');
  await say(op, `/tp PlainPlayer ${X + 0.5} ${Y + 1} ${Z - 0.5}`, 2500);
  const after = await say(pl, '/expedition leave', 1500);
  console.log('PlainPlayer after plate  :', after.slice(0, 60), after.includes('You left the expedition') ? '(PASS: plate started a run for a non-op)' : '(FAIL)');
  await say(op, `/setblock ${X} ${Y + 1} ${Z} minecraft:air`, 2500);
  op.quit(); pl.quit(); process.exit(0);
})();
