const mineflayer = require('mineflayer');
const bot = mineflayer.createBot({ host: '127.0.0.1', port: 25565, username: 'EmberTester', version: '1.21.11', auth: 'offline' });
const sleep = ms => new Promise(r => setTimeout(r, ms));
const lines = []; bot.on('message', m => lines.push(m.toString()));
const ask = async (x, w = 900) => { const n = lines.length; bot.chat(x); await sleep(w); return lines.slice(n).join(' | ').slice(0, 300); };
bot.once('spawn', async () => {
  await sleep(6500);
  await ask('/kill @e[type=!player]', 500);
  await ask('/gamemode survival'); await ask('/effect give @s minecraft:resistance 999 4 true', 300);
  await ask('/character select juggernaut', 600);
  await ask('/expedition', 1500); await sleep(1500);
  console.log('BOSS', await ask('/emberfall bossdevourer 0', 1500));
  await sleep(500);
  console.log('ITEMDISPLAYS ', await ask('/execute if entity @e[type=minecraft:item_display,distance=..80]'));
  console.log('ITEMDISPLAY N', await ask('/execute store result score @s x run execute if entity @e[type=minecraft:item_display,distance=..80]'));
  console.log('BRAIN         ', await ask('/execute if entity @e[type=emberfall:devourer_brain]'));
  console.log('TAGS          ', await ask('/data get entity @e[type=minecraft:item_display,distance=..80,limit=1] Tags'));
  console.log('DEVDUMP       ', await ask('/emberfall devdump EmberTester', 1200));
  bot.quit(); setTimeout(() => process.exit(0), 300);
});
bot.on('error', e => console.log('ERR', e.message));
